version: '3'

services:

  db:
    image: mysql:5.7
    volumes: 
      - ./db/schema.sql:/docker-entrypoint-initdb.d/1.sql
      - ./mysql:/var/lib/mysql
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
      # - MYSQL_USER=root
    networks:
      - node-network

  app:
    build:
      context: ./node
      dockerfile: Dockerfile
    container_name: app
    # entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    tty: true
    networks:
      - node-network
    ports:
      - "3000:3000"
    depends_on:
      - db
      
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    networks:
      - node-network
    ports:
      - "8080:80"
    depends_on:
      - db
      - app


networks:
  node-network:
    driver: bridge